/**
 * @deprecated This file is deprecated. Please use Tailwind CSS utility classes instead.
 * Example: Instead of TYPOGRAPHY_STYLES.textXs.medium, use 'text-xs font-medium'.
 */
export const TYPOGRAPHY_STYLES = {
  '2xl': {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '72px',
      lineHeight: '80px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '72px',
      lineHeight: '80px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '72px',
      lineHeight: '80px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '72px',
      lineHeight: '80px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  xl: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '60px',
      lineHeight: '68px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '60px',
      lineHeight: '68px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '60px',
      lineHeight: '68px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '60px',
      lineHeight: '68px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  lg: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  md: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '36px',
      lineHeight: '44px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '36px',
      lineHeight: '44px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '36px',
      lineHeight: '44px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '36px',
      lineHeight: '44px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  sm: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '30px',
      lineHeight: '38px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '30px',
      lineHeight: '38px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '30px',
      lineHeight: '38px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '30px',
      lineHeight: '38px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  xs: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '24px',
      lineHeight: '32px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '24px',
      lineHeight: '32px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '24px',
      lineHeight: '32px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '24px',
      lineHeight: '32px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textXl: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textLg: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '18px',
      lineHeight: '26px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '18px',
      lineHeight: '26px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '18px',
      lineHeight: '26px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '18px',
      lineHeight: '26px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textMd: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '16px',
      lineHeight: '24px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '16px',
      lineHeight: '24px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '16px',
      lineHeight: '24px',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '16px',
      lineHeight: '24px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textSm: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '14px',
      lineHeight: '22px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '14px',
      lineHeight: '22px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '14px',
      lineHeight: '22px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '14px',
      lineHeight: '22px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textXs: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '12px',
      lineHeight: '20px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
  },
  textSmall: {
    regular: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 400,
      fontStyle: 'normal',
      fontSize: '10px',
      lineHeight: '12px',
      letterSpacing: 0.1,
      verticalAlign: 'middle',
    },
    medium: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 500,
      fontStyle: 'normal',
      fontSize: '10px',
      lineHeight: '12px',
      letterSpacing: '0%',
      verticalAlign: 'middle',
    },
    semiBold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 600,
      fontStyle: 'normal',
      fontSize: '10px',
      lineHeight: '12px',
      letterSpacing: 0.1,
      verticalAlign: 'middle',
    },
    bold: {
      fontFamily: '"Inter",sans-serif',
      fontWeight: 700,
      fontStyle: 'normal',
      fontSize: '10px',
      lineHeight: '12px',
      letterSpacing: 0.1,
      verticalAlign: 'middle',
    },
  },
};
