export const toolbarFull = [
  'alignment',
  'uploadImage',
  'bold',
  'italic',
  'underline',
  'fontColor',
  'fontBackgroundColor',
  'link',
  'fontFamily',
  'fontSize',
  'heading',
  'blockQuote',
  'removeHighlight',
  'highlight',
  'undo',
  'redo',
  'indent',
  'outdent',
  'numberedList',
  'bulletedList',
  'mediaEmbed',
  // 'insertTable',
  // 'tableColumn',
  // 'tableRow',
  'mergeTableCells',
  'toggleTableCaption',
  'tableCellProperties',
  'underline',
];

export const toolbarMini = ['italic', 'bold', 'link', 'undo', 'redo'];
